./createAndSubmitJobs.py -q 8nh -w LXBATCH_Jobs_20Jan         -c ../bprimetobhanalysis_cfg.py -d ../datasetList.txt 
./createAndSubmitJobs.py -q 8nh -w LXBATCH_Jobs_20Jan_JESUp   -c ../bprimetobhanalysis_cfg.py -d ../datasetList_JESUp.txt 
./createAndSubmitJobs.py -q 8nh -w LXBATCH_Jobs_20Jan_JESDown -c ../bprimetobhanalysis_cfg.py -d ../datasetList_JESDown.txt 
./createAndSubmitJobs.py -q 8nh -w LXBATCH_Jobs_20Jan_JERUp   -c ../bprimetobhanalysis_cfg.py -d ../datasetList_JERUp.txt 
./createAndSubmitJobs.py -q 8nh -w LXBATCH_Jobs_20Jan_JERDown -c ../bprimetobhanalysis_cfg.py -d ../datasetList_JERDown.txt 
./createAndSubmitJobs.py -q 8nh -w LXBATCH_Jobs_20Jan_SFbUp   -c ../bprimetobhanalysis_cfg.py -d ../datasetList_SFbUp.txt 
./createAndSubmitJobs.py -q 8nh -w LXBATCH_Jobs_20Jan_SFbDown -c ../bprimetobhanalysis_cfg.py -d ../datasetList_SFbDown.txt 
./createAndSubmitJobs.py -q 8nh -w LXBATCH_Jobs_20Jan_SFlUp   -c ../bprimetobhanalysis_cfg.py -d ../datasetList_SFlUp.txt 
./createAndSubmitJobs.py -q 8nh -w LXBATCH_Jobs_20Jan_SFlDown -c ../bprimetobhanalysis_cfg.py -d ../datasetList_SFlDown.txt 
